### ISSUE TITLE
dependencies 추가

### ISSUE THREAD

**Issue by wonil112** [wonil112/guild-master#15]
추가시 마다 수정

**Comment by Gizmoring** [comment]
스프링 유효성검증 표준 사용을 위한 디펜던시 추가
implementation 'org.springframework.boot:spring-boot-starter-validation'

**Comment by Gizmoring** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip 
호환성 문제로 8.8 ver -> 7.5 downGrade
